theme: jekyll-theme-tactile

title: [Discover - Random quotes]
description: [A simple app made by Nikola Franičević]
logo: [https://github.com/FranicevicNikola/DiscoverRandomQuotes/blob/main/quote%401xna.png]
show_downloads: ["true"]
